# notam_codes.py
# Baseado na Tabela DECEA TCA 53-1 e normas ICAO
# Revisado conforme especificações do usuário

# ---------------------------------------------------------
# 2ª e 3ª Letras - ASSUNTO (O que está sendo notificado?)
# ---------------------------------------------------------
NOTAM_SUBJECT = {
    # --- AGA (AERÓDROMOS) - ILUMINAÇÃO (L) ---
    'LA': 'Sistema de luzes de aproximação',
    'LB': 'Farol de aeródromo',
    'LC': 'Luzes de eixo de pista',
    'LD': 'Iluminação do indicador de direção de pouso',
    'LE': 'Luzeslaterais de pista',
    'LF': 'Luzes de lampejossequenciais',
    'LG': 'Iluminação controlada pelo piloto',
    'LH': 'Luzes de pista de alta intensidade',
    'LI': 'Luzesidentificadoras de fim de pista',
    'LJ': 'Luzesidentificadoras de alinhamento de pista',
    'LK': 'Componentes do sistema de luzes de aproximação categoria II',
    'LL': 'Luzes de pista de baixa intensidade',
    'LM': 'Luzes de pista de média intensidade',
    'LP': 'Sistema indicador de trajetória de aproximação de precisão',
    'LR': 'Todas asinstalações de iluminação da área de pouso',
    'LS': 'Luzes de zona de parada',
    'LT': 'Luzes de cabeceira',
    'LU': 'Indicador visual da trajetória de aproximação de helicóptero',
    'LV': 'Sistema indicador da rampa de aproximação visual',
    'LW': 'Iluminação de heliporto',
    'LX': 'Luzes de eixo de pista de táxi',
    'LY': 'Luzeslaterais de pista de táxi',
    'LZ': 'Luzes de zona de toque',

    # --- AGA (AERÓDROMOS) - MOVIMENTO E POUSO (M) ---
    'MA': 'Área de movimento',
    'MB': 'Resistência de piso',
    'MC': 'Zona livre de obstáculo',
    'MD': 'Distâncias declaradas',
    'MG': 'Sistema de orientação para taxiamento',
    'MH': 'Dispositivo de parada na pista',
    'MK': 'Área de estacionamento',
    'MM': 'Sinalização diurna',
    'MN': 'Pátio',
    'MO': 'Barras de parada',
    'MP': 'Posições de aeronaves',
    'MR': 'Pista',
    'MS': 'Zona de parada',
    'MT': 'Cabeceira',
    'MU': 'Área de giro',
    'MW': 'Faixa de pista/margem da pista',
    'MX': 'Pista(s) de táxi',
    'MY': 'Pista de táxi de saída rápida',

    # --- AGA (AERÓDROMOS) - INSTALAÇÕES E SERVIÇOS (F) ---
    'FA': 'Aeródromo',
    'FB': 'Equipamento de medição de atrito',
    'FC': 'Equipamento de medição de teto',
    'FD': 'Sistema de acoplamento',
    'FE': 'Oxigênio',
    'FF': 'Combate de incêndio e salvamento',
    'FG': 'Controle de movimento no solo',
    'FH': 'Área de desembarque de Helicóptero/plataforma',
    'FI': 'Degelo de aeronaves',
    'FJ': 'Lubrificante(s)',
    'FL': 'Indicador de direção de pouso',
    'FM': 'Serviço meteorológico',
    'FO': 'Sistema de dispersão de nevoeiro',
    'FP': 'Heliporto',
    'FS': 'Equipamento de remoção de neve',
    'FT': 'Transmissômetro',
    'FU': 'Disponibilidade de combustível',
    'FW': 'Indicador de direção do vento',
    'FZ': 'Alfândega/imigração',

    # --- ATM (TRÁFEGO AÉREO) - ORGANIZAÇÃO DO ESPAÇO (A) ---
    'AA': 'Altitude mínima',
    'AC': 'Zona de controle',
    'AD': 'Zona de identificação de defesa aérea',
    'AE': 'Área de controle',
    'AF': 'Região de informação de voo',
    'AH': 'Área de controle do espaço aéreo superior',
    'AL': 'Nível de voo mínimo utilizável',
    'AN': 'Rota de navegação de área',
    'AO': 'Área de controle oceânico',
    'AP': 'Ponto de notificação',
    'AR': 'Rota de serviços de tráfego aéreo',
    'AT': 'Área de controle terminal',
    'AU': 'Região superior de informação de voo',
    'AV': 'Área de assessoramento superior',
    'AX': 'Ponto significativo',
    'AZ': 'Zona de tráfego de aeródromo',

    # --- ATM (TRÁFEGO AÉREO) - SERVIÇOS (S) ---
    'SA': 'Serviço automático de informação em terminal',
    'SB': 'Centro de notificação dosserviços de tráfego aéreo',
    'SC': 'Centro de controle de área',
    'SE': 'Serviço de informação de voo',
    'SF': 'Serviço de informação de voo de aeródromo',
    'SL': 'Centro de controle de fluxo',
    'SO': 'Centro de controle de área oceânica',
    'SP': 'Serviço de controle de aproximação',
    'SS': 'Estação de serviço de voo',
    'ST': 'Torre de controle de aeródromo',
    'SU': 'Centro de controle de área superior',
    'SV': 'Rádio de informação meteorológica para aeronave em voo',
    'SY': 'Serviço de assessoramento de área superior',

    # --- ATM (TRÁFEGO AÉREO) - PROCEDIMENTOS (P) ---
    'PA': 'Chegada padrão por instrumentos',
    'PB': 'Chegada padrão porregras de voo visual',
    'PC': 'Procedimentos de contingência',
    'PD': 'Saída padrão por instrumentos',
    'PE': 'Saída padrão porregras de voo visual',
    'PF': 'Procedimento de controle de fluxo',
    'PH': 'Procedimento de espera',
    'PI': 'Procedimento de aproximação por instrumentos',
    'PK': 'Procedimentos de aproximação por regras de voo visual',
    'PL': 'Processamento e preenchimento de plano de voo e contingência relacionada',
    'PM': 'Mínimos de operação no aeródromo',
    'PN': 'Restrições operacionais de ruído',
    'PO': 'Altitude e altura livre de obstáculo',
    'PR': 'Procedimento de falha de rádio',
    'PT': 'Altitude de transição ou nível de transição',
    'PU': 'Procedimento de aproximação perdida',
    'PX': 'Nível mínimo de espera',
    'PZ': 'Procedimento de zona de identificação de defesa aérea',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - COMUNICAÇÃO (C) ---
    'CA': 'Instalações ar-terra',
    'CB': 'Vigilância dependente automática – Radiodifusão',
    'CC': 'Vigilância dependente automática – Contrato',
    'CD': 'Comunicação porligação de dados controlador-piloto',
    'CE': 'Radar de vigilância em rota',
    'CG': 'Sistema de aproximação controlada do solo',
    'CL': 'Sistema de chamada seletiva',
    'CM': 'Radar de movimento na superfície',
    'CP': 'Radar para aproximação de precisão',
    'CR': 'Radar de vigilância que faz parte do sistema de radar para aproximação de precisão',
    'CS': 'Radar secundário de vigilância',
    'CT': 'Radar de vigilância de área terminal',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - SISTEMA DE POUSO (I) ---
    'IC': 'Sistema de pouso por instrumentos',
    'ID': 'Equipamento radiotelemétrico associado com o ILS',
    'IG': 'Trajetória de planeio (ILS)',
    'II': 'Marcador interno (ILS)',
    'IL': 'Localizador (ILS)',
    'IM': 'Marcador médio (ILS)',
    'IN': 'Localizador (não associado com ILS)',
    'IO': 'Marcador externo (ILS)',
    'IS': 'Sistema de pouso por instrumentos Categoria I',
    'IT': 'Sistema de pouso por instrumentos Categoria II',
    'IU': 'Sistema de pouso porinstrumentos Categoria III',
    'IW': 'Sistema de pouso por micro-ondas',
    'IX': 'Radiofarol de localização externo (ILS)',
    'IY': 'Radiofarol de localização médio (ILS)',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - GNSS (G) ---
    'GA': 'Operações específicas de aeródromo coberto pelo sistema mundial de navegação por satélite',
    'GW': 'Operações em toda área coberta pelo sistema mundial de navegação por satélite',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - NAVEGAÇÃO (N) ---
    'NA': 'Todas asinstalações e serviços de radionavegação',
    'NB': 'Radiofarol não-direcional',
    'ND': 'Equipamento radiotelemétrico',
    'NF': 'Radiobaliza em leque',
    'NL': 'Radiofarol de localização',
    'NM': 'RadiofarolonidirecionalemVHF/Equipamento radiotelemétrico',
    'NN': 'Auxílio à navegação aérea tática em frequência ultra-alta',
    'NT': 'Radiofarol onidirecional em VHF e Auxílio à navegação aérea tática em frequência ultra-alta combinados',
    'NV': 'Radiofarol onidirecional em VHF',
    'NX': 'Estação radiogoniométrica de frequência muito alta',

    # --- AVISOS À NAVEGAÇÃO - RESTRIÇÕES (R) ---
    'RA': 'Espaço aéreo reservado',
    'RD': 'Área perigosa',
    'RM': 'Área de operação militar',
    'RO': 'Sobrevoo de . . .',
    'RP': 'Área proibida',
    'RR': 'Área restrita',
    'RT': 'Área restrita temporariamente',

    # --- AVISOS À NAVEGAÇÃO - PERIGOS (W) ---
    'WA': 'Exibição aérea',
    'WB': 'Acrobacias aéreas',
    'WC': 'Balão cativo ou pipa',
    'WD': 'Destruição de explosivos',
    'WE': 'Exercícios',
    'WF': 'Reabastecimento aéreo',
    'WG': 'Voo planador',
    'WH': 'Dispositivo de parada na pista',
    'WJ': 'Reboque de faixa, reboque de alvo',
    'WL': 'Ascensão de balão livre',
    'WM': 'Lançamento de foguete, míssel ou disparo de arma de fogo',
    'WP': 'Exercício de salto de paraquedas, parapente ou asa delta',
    'WR': 'Materiaisradioativos ou químicos tóxicos',
    'WS': 'Explosão ou queima de gases',
    'WT': 'Movimento em massa de aeronaves',
    'WU': 'Aeronaves não tripuladas',
    'WV': 'Voo em formação',
    'WW': 'Atividade vulcânica significativa',
    'WY': 'Reconhecimento aéreo',

    # --- OUTRAS INFORMAÇÕES (O) ---
    'OA': 'Serviços de informação aeronáutica',
    'OB': 'Obstáculo',
    'OE': 'Exigências de entrada de aeronaves',
    'OL': 'Luzes de obstáculo sobre . . .',
    'OR': 'Centro de coordenação de salvamento',
    
    # --- ESPECIAL ---
    'KK': 'Lista de verificação',
    
    # --- OUTROS (X) ---
    'XX': 'Linguagem clara'
}

# ---------------------------------------------------------
# 4ª e 5ª Letras - CONDIÇÃO (Qual é o estado?)
# ---------------------------------------------------------
NOTAM_CONDITION = {
    # --- DISPONIBILIDADE (A) ---
    'AC': 'Retirado para manutenção',
    'AD': 'Disponível para operação diurna',
    'AF': 'Inspecionado em voo e considerado confiável',
    'AG': 'Operacional, mas somente verificado em solo, à espera de inspeção em voo',
    'AH': 'O horário de funcionamento é',
    'AK': 'Operação normal retomada',
    'AL': 'Operante (ou reoperante) sujeito a limitações/condições anteriormente publicadas',
    'AM': 'Somente para operações militares',
    'AN': 'Disponível para operação noturna',
    'AO': 'Operacional',
    'AP': 'Disponível,requer autorização prévia',
    'AR': 'Disponível a pedido',
    'AS': 'Não utilizável',
    'AU': 'Não disponível',
    'AW': 'Retirado completamente',
    'AX': 'Cancelado o desligamento anteriormente divulgado',

    # --- MODIFICAÇÕES (C) ---
    'CA': 'Ativado',
    'CC': 'Concluído',
    'CD': 'Desativado',
    'CE': 'Montado',
    'CF': 'Frequência(s) de operaçãomodificada(s) para',
    'CG': 'Reduzido para',
    'CH': 'Modificado',
    'CI': 'Identificação rádio modificada para ou indicativo de chamada por rádio modificada para',
    'CL': 'Realinhado',
    'CM': 'Deslocado',
    'CN': 'Cancelado',
    'CO': 'Em operação',
    'CP': 'Operando com potência reduzida',
    'CR': 'Temporariamente substituído por',
    'CS': 'Instalado',
    'CT': 'Em teste, não use',

    # --- CONDIÇÕES DE PERIGO (H) ---
    'HA': 'Ação de frenagem é',
    'HB': 'Coeficiente de Fricção é',
    'HC': 'Coberto por neve compacta a uma profundidade de',
    'HD': 'Coberto por neve seca a uma profundidade de',
    'HE': 'Coberto por água a uma profundidade de',
    'HF': 'Totalmente livre de gelo e neve',
    'HG': 'Corte de grama em andamento',
    'HH': 'Perigo devido a (especificar)',
    'HI': 'Coberto por gelo',
    'HJ': 'Lançamento planejado',
    'HK': 'Migração de pássaros em curso',
    'HL': 'Limpeza de neve concluída',
    'HM': 'Marcado por',
    'HN': 'Coberto por neve úmida ou neve semiderretida a uma profundidade de',
    'HO': 'Encoberto pela neve',
    'HQ': 'Operação cancelada',
    'HR': 'Água parada',
    'HS': 'Lixamento em progresso',
    'HT': 'Aproximação somente de acordo com área de sinais',
    'HU': 'Lançamento em andamento',
    'HV': 'Obras concluídas',
    'HW': 'Obras em andamento',
    'HX': 'Concentração de pássaros',
    'HY': 'Existem bancos de neve (especificar a altura)',
    'HZ': 'Coberto porsulcos e cumes congelados',

    # --- LIMITAÇÕES (L) ---
    'LA': 'Operando com fonte de energia auxiliar',
    'LB': 'Reservado para aeronaveslocais',
    'LC': 'Fechado',
    'LD': 'Inseguro',
    'LE': 'Operando sem força auxiliar',
    'LF': 'Interferência de',
    'LG': 'Operando sem identificação',
    'LH': 'Não utilizável para aeronaves mais pesadas que',
    'LI': 'Fechado para operações com regras de voo por instrumentos',
    'LK': 'Operando com uma luz fixa',
    'LL': 'Utilizável com o comprimento de . . . e a largura de . . .',
    'LN': 'Fechado para todas as operações noturnas',
    'LP': 'Proibido para',
    'LR': 'Aeronavesrestritas às pistas e pistas de táxi',
    'LS': 'Sujeito à interrupção',
    'LT': 'Limitado para',
    'LV': 'Fechado para operações com regras de voo visual',
    'LW': 'Acontecerá',
    'LX': 'Operando, mas com cautela devido a',

    # --- OUTROS (X) ---
    'XX': 'Linguagem clara'
}