# notam_codes.py
# Baseado na Tabela DECEA TCA 53-1 (Anexo I)

# ---------------------------------------------------------
# 2ª e 3ª Letras - ASSUNTO (O que está sendo notificado?)
# ---------------------------------------------------------
NOTAM_SUBJECT = {
    # --- AGA (AERÓDROMOS) - ILUMINAÇÃO (L) ---
    'LA': 'Sistema de luzes de aproximação (ALS)',
    'LB': 'Farol de aeródromo (Aerodrome Beacon)',
    'LC': 'Luzes de eixo de pista (RCLL)',
    'LD': 'Iluminação do indicador de direção de pouso (LDI)',
    'LE': 'Luzes laterais de pista (REDL)',
    'LF': 'Luzes de lampejos sequenciais',
    'LG': 'Iluminação controlada pelo piloto (PCL)',
    'LH': 'Luzes de pista de alta intensidade',
    'LI': 'Luzes identificadoras de fim de pista (REIL)',
    'LJ': 'Luzes identificadoras de alinhamento de pista (RAI)',
    'LK': 'Componentes do sistema de luzes de aproximação Categoria II',
    'LL': 'Luzes de pista de baixa intensidade',
    'LM': 'Luzes de pista de média intensidade',
    'LP': 'Sistema indicador de trajetória de aproximação de precisão (PAPI)',
    'LR': 'Todas as instalações de iluminação da área de pouso',
    'LS': 'Luzes de zona de parada',
    'LT': 'Luzes de cabeceira',
    'LU': 'Indicador visual da trajetória de aproximação de helicóptero (HAPI)',
    'LV': 'Sistema indicador da rampa de aproximação visual (VASIS)',
    'LW': 'Iluminação de heliporto',
    'LX': 'Luzes de eixo de pista de táxi',
    'LY': 'Luzes laterais de pista de táxi',
    'LZ': 'Luzes de zona de toque (RTZL)',

    # --- AGA (AERÓDROMOS) - MOVIMENTO E POUSO (M) ---
    'MA': 'Área de movimento',
    'MB': 'Resistência de piso (Bearing Strength)',
    'MC': 'Zona livre de obstáculo (Clearway)',
    'MD': 'Distâncias declaradas (TORA/TODA/ASDA/LDA)',
    'MG': 'Sistema de orientação para taxiamento',
    'MH': 'Dispositivo de parada na pista (Arresting Gear)',
    'MK': 'Área de estacionamento',
    'MM': 'Sinalização diurna',
    'MN': 'Pátio (Apron)',
    'MO': 'Barras de parada (Stopbar)',
    'MP': 'Posições de estacionamento de aeronaves (Stands)',
    'MR': 'Pista (Runway)',
    'MS': 'Zona de parada (Stopway)',
    'MT': 'Cabeceira (Threshold)',
    'MU': 'Área de giro (Turning Bay)',
    'MW': 'Faixa de pista / Margem da pista (Strip/Shoulder)',
    'MX': 'Pista(s) de táxi (Taxiway)',
    'MY': 'Pista de táxi de saída rápida',

    # --- AGA (AERÓDROMOS) - INSTALAÇÕES E SERVIÇOS (F) ---
    'FA': 'Aeródromo',
    'FB': 'Equipamento de medição de atrito',
    'FC': 'Equipamento de medição de teto',
    'FD': 'Sistema de acoplamento (Docking System)',
    'FE': 'Oxigênio',
    'FF': 'Combate de incêndio e salvamento',
    'FG': 'Controle de movimento no solo',
    'FH': 'Área de desembarque de Helicóptero / Plataforma',
    'FI': 'Degelo de aeronaves',
    'FJ': 'Óleos / Lubrificantes',
    'FL': 'Indicador de direção de pouso (LDI)',
    'FM': 'Serviço meteorológico',
    'FO': 'Sistema de dispersão de nevoeiro',
    'FP': 'Heliporto',
    'FS': 'Equipamento de remoção de neve',
    'FT': 'Transmissômetro',
    'FU': 'Disponibilidade de combustível',
    'FW': 'Indicador de direção do vento (Biruta)',
    'FZ': 'Alfândega / Imigração',

    # --- ATM (TRÁFEGO AÉREO) - ORGANIZAÇÃO DO ESPAÇO (A) ---
    'AA': 'Altitude mínima',
    'AC': 'Zona de controle (CTR)',
    'AD': 'Zona de identificação de defesa aérea (ADIZ)',
    'AE': 'Área de controle (CTA)',
    'AF': 'Região de informação de voo (FIR)',
    'AH': 'Área de controle superior (UTA)',
    'AL': 'Nível de voo mínimo utilizável',
    'AN': 'Rota de navegação de área (RNAV)',
    'AO': 'Área de controle oceânico (OCA)',
    'AP': 'Ponto de notificação (Reporting Point)',
    'AR': 'Rota ATS',
    'AT': 'Área de controle terminal (TMA)',
    'AU': 'Região superior de informação de voo (UIR)',
    'AV': 'Área de assessoramento superior (UDA)',
    'AX': 'Ponto significativo',
    'AZ': 'Zona de tráfego de aeródromo (ATZ)',

    # --- ATM (TRÁFEGO AÉREO) - SERVIÇOS (S) ---
    'SA': 'Serviço automático de informação de terminal (ATIS)',
    'SB': 'Sala AIS (ATS Reporting Office)',
    'SC': 'Centro de controle de área (ACC)',
    'SE': 'Serviço de informação de voo (FIS)',
    'SF': 'Serviço de informação de voo de aeródromo (AFIS)',
    'SL': 'Centro de controle de fluxo',
    'SO': 'Centro de controle de área oceânica (OAC)',
    'SP': 'Serviço de controle de aproximação (APP)',
    'SS': 'Estação de serviço de voo (FSS)',
    'ST': 'Torre de controle de aeródromo (TWR)',
    'SU': 'Centro de controle de área superior (UACC)',
    'SV': 'VOLMET',
    'SY': 'Serviço de assessoramento de área superior',

    # --- ATM (TRÁFEGO AÉREO) - PROCEDIMENTOS (P) ---
    'PA': 'Chegada padrão por instrumentos (STAR)',
    'PB': 'Chegada padrão visual (VFR)',
    'PC': 'Procedimentos de contingência',
    'PD': 'Saída padrão por instrumentos (SID)',
    'PE': 'Saída padrão visual (VFR)',
    'PF': 'Procedimento de controle de fluxo',
    'PH': 'Procedimento de espera',
    'PI': 'Procedimento de aproximação por instrumentos (IAP)',
    'PK': 'Procedimento de aproximação visual (VFR)',
    'PL': 'Plano de voo (FPL)',
    'PM': 'Mínimos de operação no aeródromo',
    'PN': 'Restrições operacionais de ruído',
    'PO': 'Altitude/Altura livre de obstáculos',
    'PR': 'Procedimento de falha de rádio',
    'PT': 'Altitude de transição ou nível de transição',
    'PU': 'Procedimento de aproximação perdida',
    'PX': 'Nível mínimo de espera',
    'PZ': 'Procedimento ADIZ',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - COMUNICAÇÃO (C) ---
    'CA': 'Instalações ar-terra (A/G)',
    'CB': 'ADS-B',
    'CC': 'ADS-C',
    'CD': 'CPDLC',
    'CE': 'Radar de vigilância em rota (RSR)',
    'CG': 'Sistema de aproximação controlada do solo (GCA)',
    'CL': 'Sistema de chamada seletiva (SELCAL)',
    'CM': 'Radar de movimento na superfície (SMR)',
    'CP': 'Radar de aproximação de precisão (PAR)',
    'CR': 'Elemento de vigilância do radar de precisão (SRE)',
    'CS': 'Radar secundário de vigilância (SSR)',
    'CT': 'Radar de vigilância de área terminal (TAR)',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - SISTEMA DE POUSO (I) ---
    'IC': 'Sistema de pouso por instrumentos (ILS)',
    'ID': 'DME associado ao ILS',
    'IG': 'Trajetória de planeio (Glide Path)',
    'II': 'Marcador interno (Inner Marker)',
    'IL': 'Localizador (ILS)',
    'IM': 'Marcador médio (Middle Marker)',
    'IN': 'Localizador não associado ao ILS',
    'IO': 'Marcador externo (Outer Marker)',
    'IS': 'ILS Categoria I',
    'IT': 'ILS Categoria II',
    'IU': 'ILS Categoria III',
    'IW': 'Sistema de pouso por micro-ondas (MLS)',
    'IX': 'Locator Outer (LO)',
    'IY': 'Locator Middle (LM)',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - GNSS (G) ---
    'GA': 'GNSS (Operações de aeródromo)',
    'GW': 'GNSS (Operações em área)',

    # --- CNS (COMUNICAÇÃO/NAVEGAÇÃO) - NAVEGAÇÃO (N) ---
    'NA': 'Todas instalações de radionavegação',
    'NB': 'Radiofarol não-direcional (NDB)',
    'ND': 'DME',
    'NF': 'Radiobaliza em leque (Fan Marker)',
    'NL': 'Radiofarol de localização (Locator)',
    'NM': 'VOR/DME',
    'NN': 'TACAN',
    'NT': 'VORTAC',
    'NV': 'VOR',
    'NX': 'Estação radiogoniométrica (DF)',

    # --- AVISOS À NAVEGAÇÃO - RESTRIÇÕES (R) ---
    'RA': 'Espaço aéreo reservado',
    'RD': 'Área perigosa (Danger)',
    'RM': 'Área de operação militar (MOA)',
    'RO': 'Sobrevoo',
    'RP': 'Área proibida',
    'RR': 'Área restrita',
    'RT': 'Área restrita temporariamente',

    # --- AVISOS À NAVEGAÇÃO - PERIGOS (W) ---
    'WA': 'Exibição aérea',
    'WB': 'Acrobacias aéreas',
    'WC': 'Balão cativo ou pipa',
    'WD': 'Destruição de explosivos',
    'WE': 'Exercícios Militares/Navais',
    'WF': 'Reabastecimento aéreo',
    'WG': 'Voo de planador',
    'WH': 'Detonação de explosivos (Blasting)',
    'WJ': 'Reboque de faixa/alvo',
    'WL': 'Ascensão de balão livre',
    'WM': 'Lançamento de foguete/míssil ou tiro',
    'WP': 'Salto de paraquedas / Parapente / Asa delta',
    'WR': 'Materiais radioativos ou químicos tóxicos',
    'WS': 'Explosão ou queima de gases',
    'WT': 'Movimento em massa de aeronaves',
    'WU': 'Aeronaves não tripuladas (Drones/UA)',
    'WV': 'Voo em formação',
    'WW': 'Atividade vulcânica',
    'WY': 'Reconhecimento aéreo',

    # --- OUTRAS INFORMAÇÕES (O) ---
    'OA': 'Serviço de Informação Aeronáutica (AIS)',
    'OB': 'Obstáculo',
    'OE': 'Exigências de entrada de aeronaves',
    'OL': 'Luzes de obstáculo',
    'OR': 'Centro de coordenação de salvamento (RCC)',
    
    # --- ESPECIAL ---
    'KK': 'Lista de Verificação (Checklist)'
}

# ---------------------------------------------------------
# 4ª e 5ª Letras - CONDIÇÃO (Qual é o estado?)
# ---------------------------------------------------------
NOTAM_CONDITION = {
    # --- DISPONIBILIDADE (A) ---
    'AC': 'Retirado para manutenção',
    'AD': 'Disponível para operação diurna',
    'AF': 'Inspecionado em voo e considerado confiável',
    'AG': 'Operacional mas verificado apenas em solo',
    'AH': 'Horário de funcionamento modificado',
    'AK': 'Operação normal retomada',
    'AL': 'Operante sujeito a limitações anteriores',
    'AM': 'Somente para operações militares',
    'AN': 'Disponível para operação noturna',
    'AO': 'Operacional',
    'AP': 'Disponível, requer autorização prévia (PPR)',
    'AR': 'Disponível a pedido (O/R)',
    'AS': 'Inoperante (U/S)',
    'AU': 'Não disponível',
    'AW': 'Retirado completamente',
    'AX': 'Desligamento cancelado',

    # --- MODIFICAÇÕES (C) ---
    'CA': 'Ativado',
    'CC': 'Concluído',
    'CD': 'Desativado',
    'CE': 'Montado (Erected)',
    'CF': 'Frequência de operação modificada',
    'CG': 'Reduzido para (Downgraded)',
    'CH': 'Modificado',
    'CI': 'Identificação ou indicativo de chamada modificado',
    'CL': 'Realinhado',
    'CM': 'Deslocado (Displaced)',
    'CN': 'Cancelado',
    'CO': 'Em operação',
    'CP': 'Operando com potência reduzida',
    'CR': 'Temporariamente substituído por',
    'CS': 'Instalado',
    'CT': 'Em teste, não use',

    # --- CONDIÇÕES DE PERIGO (H) ---
    'HA': 'Ação de frenagem é...',
    'HB': 'Coeficiente de fricção é...',
    'HC': 'Coberto por neve compacta',
    'HD': 'Coberto por neve seca',
    'HE': 'Coberto por água',
    'HF': 'Livre de gelo e neve',
    'HG': 'Corte de grama em andamento',
    'HH': 'Perigo devido a...',
    'HI': 'Coberto por gelo',
    'HK': 'Migração de pássaros / Lançamento de balão',
    'HL': 'Limpeza de neve concluída',
    'HM': 'Marcado por',
    'HN': 'Coberto por neve úmida/semiderretida',
    'HO': 'Encoberto pela neve',
    'HQ': 'Operação cancelada',
    'HR': 'Água parada',
    'HS': 'Lixamento em progresso',
    'HT': 'Aproximação conforme área de sinais',
    'HU': 'Lançamento em andamento',
    'HV': 'Obras concluídas',
    'HW': 'Obras em andamento (WIP)',
    'HX': 'Concentração de pássaros',
    'HY': 'Bancos de neve existem',
    'HZ': 'Coberto por sulcos ou cumes congelados',

    # --- LIMITAÇÕES (L) ---
    'LA': 'Operando com fonte de energia auxiliar',
    'LB': 'Reservado para aeronaves locais/baseadas',
    'LC': 'Fechado (Closed)',
    'LD': 'Inseguro',
    'LE': 'Operando sem força auxiliar',
    'LF': 'Interferência de...',
    'LG': 'Operando sem identificação',
    'LH': 'Não utilizável para aeronaves pesadas',
    'LI': 'Fechado para IFR',
    'LK': 'Operando como luz fixa',
    'LL': 'Utilizável com comprimento/largura reduzidos',
    'LN': 'Fechado para operações noturnas',
    'LP': 'Proibido para...',
    'LR': 'Aeronaves restritas às pistas e taxiways',
    'LS': 'Sujeito à interrupção',
    'LT': 'Limitado para...',
    'LV': 'Fechado para VFR',
    'LW': 'Acontecerá (Will take place)',
    'LX': 'Operando com cautela',

    # --- OUTROS (X) ---
    'XX': 'Outros (Linguagem Clara / Ver Texto)'
}